/**
 * エラーのカテゴリー定義
 */
export const ERROR_CATEGORIES = {
  SETUP_REQUIRED: 'SETUP_REQUIRED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  NETWORK_ERROR: 'NETWORK_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCategory =
  (typeof ERROR_CATEGORIES)[keyof typeof ERROR_CATEGORIES];

/**
 * 具体的なエラーコード定義
 */
export const ERROR_CODES = {
  // セットアップ関連
  VRCHAT_DIRECTORY_SETUP_REQUIRED: 'VRCHAT_DIRECTORY_SETUP_REQUIRED',
  PHOTO_DIRECTORY_SETUP_REQUIRED: 'PHOTO_DIRECTORY_SETUP_REQUIRED',

  // ファイル/ディレクトリアクセス関連
  VRCHAT_LOGS_ACCESS_DENIED: 'VRCHAT_LOGS_ACCESS_DENIED',
  PHOTO_DIRECTORY_ACCESS_DENIED: 'PHOTO_DIRECTORY_ACCESS_DENIED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',

  // データベース関連
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  DATABASE_MIGRATION_FAILED: 'DATABASE_MIGRATION_FAILED',
  DATABASE_ERROR: 'DATABASE_ERROR',

  // バリデーション関連
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // 一般的なエラー
  INITIALIZATION_FAILED: 'INITIALIZATION_FAILED',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
